- name: Check if zsh is present
  command: /bin/sh -c "command -v zsh >/dev/null 2>&1"
  register: zsh_installed
  ignore_errors: yes

- name: Install zsh
  ansible.builtin.apt:
    name: zsh
    state: present
    update_cache: yes
  when: zsh_installed.rc != 0

- name: Create the group
  ansible.builtin.group:
    name: "{{ username }}"
    state: present

- name: Create the user
  ansible.builtin.user:
    name: "{{ username }}"
    comment: "{{ user_detail }}"
    home: "{{ username }}"
    group: "{{ username }}"
    groups: "{{ user_groups }}"
    password: "{{ user_password | password_hash('sha512', 'saltIDontCareAboutBecauseTheHashWillNotBeStored') }}"
    generate_ssh_key: true
    ssh_key_type: ed25519
    ssh_key_passphrase: "{{ ssh_key_passphrase }}"
    ssh_key_comment: "{{ ansible_hostname }}"
    shell: /bin/zsh
  register: user_info


- name: Print the home directory
  ansible.builtin.debug:
    msg: "User's home is :\n{{ user_info.home }}"

- name: Print the public key
  ansible.builtin.debug:
    msg: "User's public key is :\n{{ user_info.ssh_public_key }}"

- name: Check if oh-my-zsh is already installed
  stat:
    path: "{{ user_info.home }}/.oh-my-zsh"
  register: oh_my_zsh_dir
  
- name: Download oh-my-zsh installer
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/zsh-installer.sh
    mode: "0755"
  when: not oh_my_zsh_dir.stat.exists
  register: download

- name: Run the oh-my-zsh installer
  shell: /tmp/zsh-installer.sh --unattended
  when: not oh_my_zsh_dir.stat.exists and download.changed
  become_user: "{{ username }}"

- name: Remove the oh-my-zsh installer
  file:
    path: /tmp/zsh-installer.sh
    state: absent

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ user_info.home }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ user_info.home }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: Setup zsh configuration
  ansible.builtin.template:
    src: .zshrc
    dest: "{{ user_info.home }}/.zshrc"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0640'