- hosts: all
  become: true
  vars:

  vars_prompt:
    - name: username
      prompt: What is your username ?
      private: false
    - name: user_detail
      prompt: What is the user description ?
    - name: user_password
      prompt: What is your user password ?
      private: true
    - name: ssh_key_passphrase
      prompt: What is the passphrase for the ssh key ?
      private: true
  roles:
    - setup-env